### ISSUE TITLE
재생이 완료되면 재생 버튼을 눌러도 아무 반응이 없음

### ISSUE THREAD

**Issue by Reviviscence** [Reviviscence/Sceneclipse#5]
* 재생이 완료되고 나면 재생 버튼을 누르거나 시크바를 움직여도 아무 반응이 없으며, 파일을 새로 열어야지만 다시 재생되어 불편함

**Comment by th-kwon** [comment]
Commit 1e80bbd8aa17cb81953249f181c31d46fa086c96 에서 수정 완료
